OLD_HOMBREW_PREFIX=/usr/local
NEW_HOMBREW_PREFIX=/opt/homebrew
if [ -d "$NEW_HOMBREW_PREFIX" ]; then
    export HOMEBREW_NO_ANALYTICS=1
    export HOMEBREW_PREFIX="$NEW_HOMBREW_PREFIX"
    export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH"
else
    export HOMEBREW_NO_ANALYTICS=1
    export HOMEBREW_PREFIX="$OLD_HOMBREW_PREFIX"
    export PATH="$HOMEBREW_PREFIX/bin:$HOMEBREW_PREFIX/sbin:$PATH"
fi
